repos:
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest -v # execute pytest on commit
      always_run: true
      pass_filenames: false
      stages: [commit] # apply pytest on commit stage
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv/bin/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit] # update requirements.txt on commit stage